name: Question
description: Need help on usage?
title: "[QUESTION] "
assignees:
  - lippertmarkus
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe what you need help with.
    validations:
      required: true
