name: Question
description: Need help with usage?
title: "[QUESTION] "
labels:
  - question
assignees:
  - lippertmarkus
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe what you need help with.
    validations:
      required: true
